### ISSUE TITLE
Inconsistent behavior with multiple `npm-install` steps in single pipeline

### ISSUE THREAD

**Issue by marshall007** [wercker/step-npm-install#12]
With the following `wercker.yml` config, the second `npm-install` step reuses the options passed into the first. However, if you flip the order, it works as expected.

```yml
box: node

build:
  steps:
    - add-to-known_hosts:
        hostname: github.com
        fingerprint: ...

    - add-ssh-key:
        keyname: GITHUB

    - npm-install:
        options: -g git+ssh://git@github.com:nextgxdx/brick.git#v1.0.4
    - npm-install
```

**Comment by hatchan** [comment]
This is cuased by the fact that we do not unset the environment variables after a step. Thanks for reporting this issue, I'll create a ticket for it.

**Comment by termie** [comment]
Hi there, is this on the classic stack or on the docker stack? On the docker stack I am not seeing this behavior

```
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm@2.14.13 /usr/lib/node_modules/npm
Finished npm install
--> Running step: script
WERCKER_NPM_INSTALL_OPTIONS=-g npm@latest-2
WERCKER_NPM_INSTALL_CLEAR_CACHE_ON_FAILED=true
WERCKER_NPM_INSTALL_USE_CACHE=true
--> Running step: npm-install
Using wercker cache
Creating $WERCKER_CACHE_DIR/wercker/npm
Configuring npm to use wercker cache
Starting npm install, try: 1
cron@1.0.9 node_modules/cron
└── moment-timezone@0.3.1 (moment@2.10.6)
Finished npm install
--> Running step: script
WERCKER_NPM_INSTALL_OPTIONS=
WERCKER_NPM_INSTALL_CLEAR_CACHE_ON_FAILED=true
WERCKER_NPM_INSTALL_USE_CACHE=true
--> Steps passed: 11.45s
--> Pipeline finished: 12.48s
```

using this wercker.yml
```
test_npm:
  box: nodesource/trusty:0.10
  steps:
    - npm-install:
        options: -g npm@latest-2
    - script:
        code: env | grep "NPM"

    - npm-install
    - script:
        code: env | grep "NPM"
```
