### ISSUE TITLE
postinstall silently fails

### ISSUE THREAD

**Issue by twolfson** [wercker/step-npm-install#14]
I have a private repo set up with a `postinstall` hook to handle automatic bower installation and compiling of developer assets. In the following setup, I receive this message but wercker continues to pass but doesn't fail:

**Error message:**

```
npm WARN cannot run in wd app@1.0.0 bower install && npm run build (wd=/pipeline/source)
```

**package.json:**

```json
{
  "scripts": {
    "build": "gulp build-clean && gulp build",
    "postinstall": "bower install && npm run build",
  }
}
```

**wercker.yml:**

```yml
# Configure our container
box: node:4.4

# Define our build steps (e.g. test steps)
build:
  steps:
    # Output our Node.js and npm versions
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

    # Install our dependencies and dev dependencies
    # DEV: This also tests `npm run build` due to a `postinstall` hook
    - npm-install

    # Run our tests
    - npm-test
```

After doing some digging, it turns out this error message is caused by `npm` wanting to drop root permissions (as a good program should). Unfortunately, it doesn't look like wercker/Docker are set up for that so we have to work around it.

To get it patched, I added a config to allow root/sudo permissions for both `npm` and `bower` (`bower` gets a similar `ESUDO` error):

**Reference links:**

- https://github.com/npm/npm/issues/3497
- https://github.com/bower/bower/issues/1752#issuecomment-113455403

**Patched wercker.yml:**

```yml
# Configure our container
box: node:4.4

# Define our build steps (e.g. test steps)
build:
  steps:
    # Output our Node.js and npm versions
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

    # Configure npm and bower to allow root scripts
    - script:
        name: enable root/sudo for npm/bower
        code: |
          # https://docs.npmjs.com/misc/config#unsafe-perm
          npm config set unsafe-perm true
          # https://github.com/bower/bower/issues/1752#issuecomment-113455403
          echo "{\"allow_root\": true}" > ~/.bowerrc

    # Install our dependencies and dev dependencies
    # DEV: This also tests `npm run build` due to a `postinstall` hook
    - npm-install@1.1.4

    # Run our tests
    - npm-test@0.0.3
```

I feel like there should be something baked into wercker to handle this (e.g. run as a non-root user) but I think you folks will have better ideas.
