### ISSUE TITLE
Does not install devDependencies

### ISSUE THREAD

**Issue by siddharthkp** [wercker/step-npm-install#23]
I have noticed this in [my builds](https://app.wercker.com/siddharthkp/ci-env/runs), `step-npm-install` does not install dev dependencies which causes my tests to fail.

**Comment by siddharthkp** [comment]
This is because the environment is set to `production`

This workaround worked for me:

```
- script:
        name: set production false
        code: |
          npm config set -g production false

- npm-install
```
